name: mlfood-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterhub
  - pydot
  - graphviz
  - psutil
  - opencv
  - pip
  - pip:
    - jupyter
    - tensorflow==2.3.1
    - git+git://github.com/GiuseppeDiGuglielmo/hls4ml.git@gdg/cosmetics#egg=hls4ml[profiling]
    - git+git://github.com/google/qkeras.git#egg=qkeras

#- hls4ml[profiling]==0.4.0
